<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="K-ASHIK-L1" name="timeOutTest.timeOuttestInTestNg" tests="2" failures="0" timestamp="31 Dec 2020 08:45:23 GMT" time="1.059" errors="1">
  <testcase name="executetimeOut" time="1.057" classname="timeOutTest.timeOuttestInTestNg">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method timeOutTest.timeOuttestInTestNg.executetimeOut() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method timeOutTest.timeOuttestInTestNg.executetimeOut() didn't finish within the time-out 1000
at sun.misc.Unsafe.compareAndSwapInt(Native Method)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.compareAndSetState(Unknown Source)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(Unknown Source)
at java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- executetimeOut -->
  <testcase name="sampleTestCase" time="0.002" classname="timeOutTest.timeOuttestInTestNg"/>
</testsuite> <!-- timeOutTest.timeOuttestInTestNg -->
